application: bionic-unity-106416
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /media
  static_dir: media

- url: /js
  static_dir: js

- url: .*
  script: learningatudacity.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest